console.log("hello");
document.getElementById("button").click();
document.getElementById("button").style.fontSize="20px";
document.getElementById("submit").style.fontSize="20px";
document.getElementById("para").style.border="5px solid blue";
let elem=document.getElementById('para');
console.log(elem);
elem.style.background="green";
elem.classList.add("bg-primary");
elem.classList.add("text-success");
elem.classList.remove("text-success");
let hed=document.getElementById("heading");
console.log(hed);
console.log(hed.innerHTML);
console.log(hed.innerText);
console.log(elem.innerHTML);
let btn1= (document.getElementsByClassName("btn"));
console.log(btn1);
tn=document.getElementsByTagName('div');
console.log(tn);
createdElement=document.createElement('p');
createdElement.innertext="this is new created parra";
tn[0].appendChild(createdElement);
cont=document.getElementsByClassName('container');
console.log(cont);
ce=document.createElement('p');
ce.innertext="this is new created parra";
ce.appendChild(createdElement);